"""Excel report builder (Stream 6).

Uses openpyxl (already in requirements). Produces a styled .xlsx with:
  • Title sheet ("Summary") describing the query and execution metadata
  • Data sheet ("Results") with header styling + autosized columns
  • Numeric / date formatting where applicable

Files are written under UPLOAD_DIR/reports/<report_id>.xlsx and served via the
reports download endpoint.
"""
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from core.config import UPLOAD_DIR

logger = logging.getLogger("docchat.db_agent.excel_exporter")

REPORTS_DIR = UPLOAD_DIR / "db_agent_reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


HEADER_FILL = PatternFill(start_color="0033A0", end_color="0033A0", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True, name="Calibri", size=11)


def _fit_columns(ws, max_width: int = 60) -> None:
    for col_idx, column_cells in enumerate(ws.columns, start=1):
        max_len = 0
        for cell in column_cells:
            v = cell.value
            if v is None:
                continue
            s = str(v)
            if len(s) > max_len:
                max_len = len(s)
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max(12, max_len + 2), max_width)


def build_xlsx(
    report_id: str,
    natural_query: str,
    sql: str,
    explanation: str,
    result: dict,
    user_email: str | None = None,
) -> str:
    wb = Workbook()

    # ── Summary sheet ────────────────────────────────────────────────────────
    summary = wb.active
    summary.title = "Summary"
    summary.append(["DocChat – DB Agent Report"])
    summary["A1"].font = Font(bold=True, size=14, name="Calibri")
    summary.append([])
    summary.append(["Generated", datetime.now(timezone.utc).isoformat()])
    summary.append(["Generated by", user_email or "—"])
    summary.append(["Row count", result.get("row_count", 0)])
    summary.append(["Elapsed (ms)", result.get("elapsed_ms", 0)])
    summary.append([])
    summary.append(["Natural-language query"])
    summary["A8"].font = Font(bold=True)
    summary.append([natural_query])
    summary.append([])
    summary.append(["Generated SQL"])
    summary["A11"].font = Font(bold=True)
    summary.append([sql])
    summary.append([])
    summary.append(["Explanation"])
    summary["A14"].font = Font(bold=True)
    summary.append([explanation])
    summary.column_dimensions["A"].width = 24
    summary.column_dimensions["B"].width = 80
    for row in summary.iter_rows():
        for cell in row:
            cell.alignment = Alignment(wrap_text=True, vertical="top")

    # ── Results sheet ────────────────────────────────────────────────────────
    results_sheet = wb.create_sheet("Results")
    columns = result.get("columns") or []
    rows = result.get("rows") or []
    if columns:
        results_sheet.append(columns)
        for cell in results_sheet[1]:
            cell.fill = HEADER_FILL
            cell.font = HEADER_FONT
            cell.alignment = Alignment(horizontal="left", vertical="center")
        for r in rows:
            results_sheet.append([_normalize_cell(r.get(c)) for c in columns])
        _fit_columns(results_sheet)
        results_sheet.freeze_panes = "A2"
    else:
        results_sheet.append(["(no rows returned)"])

    # Persist
    path = REPORTS_DIR / f"{report_id}.xlsx"
    wb.save(path)
    return str(path)


def _normalize_cell(v: Any):
    if v is None:
        return None
    if isinstance(v, (str, int, float, bool)):
        return v
    if isinstance(v, datetime):
        return v.replace(tzinfo=None) if v.tzinfo else v
    return str(v)
